// <auto-generated />
using System;
using KrutangerHighSchoolDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrutangerHighSchoolDB.Migrations
{
    [DbContext(typeof(KrutångerHighSchoolContext))]
    [Migration("20231215082434_AddLatestMonthGradesView")]
    partial class AddLatestMonthGradesView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.ClassList", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("Branch")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClassName")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.HasKey("ClassId");

                    b.ToTable("ClassList", (string)null);
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.ClassMentor", b =>
                {
                    b.Property<int?>("FkClassId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ClassId");

                    b.Property<int?>("FkPersonnelId")
                        .HasColumnType("int")
                        .HasColumnName("FK_PersonnelId");

                    b.HasIndex("FkClassId");

                    b.HasIndex("FkPersonnelId");

                    b.ToTable("ClassMentor", (string)null);
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Course1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Course");

                    b.HasKey("CourseId");

                    b.ToTable("SeeCourses");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.CourseRegistration", b =>
                {
                    b.Property<int>("CourseRegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseRegId"));

                    b.Property<int?>("FkCourseId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CourseId");

                    b.Property<int?>("FkStudentId")
                        .HasColumnType("int")
                        .HasColumnName("FK_StudentId");

                    b.HasKey("CourseRegId");

                    b.HasIndex("FkCourseId");

                    b.HasIndex("FkStudentId");

                    b.ToTable("CourseRegistration", (string)null);
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.CourseTeacher", b =>
                {
                    b.Property<int>("CourseTeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseTeacherId"));

                    b.Property<int?>("FkCourseId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CourseId");

                    b.Property<int?>("FkPersonnelId")
                        .HasColumnType("int")
                        .HasColumnName("FK_PersonnelId");

                    b.HasKey("CourseTeacherId");

                    b.HasIndex("FkCourseId");

                    b.HasIndex("FkPersonnelId");

                    b.ToTable("CourseTeacher", (string)null);
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Gender", b =>
                {
                    b.Property<byte>("GenderChoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("GenderChoice"));

                    b.Property<string>("Gender1")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Gender");

                    b.HasKey("GenderChoice")
                        .HasName("PK__Genders__4E24E9F7FF3B3015");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Grade", b =>
                {
                    b.Property<int>("GradedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradedId"));

                    b.Property<int?>("FkCourseRegId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CourseRegId");

                    b.Property<int?>("FkCourseTeacherId")
                        .HasColumnType("int")
                        .HasColumnName("FK_CourseTeacherId");

                    b.Property<byte?>("FkGradeId")
                        .HasColumnType("tinyint")
                        .HasColumnName("FK_GradeId");

                    b.Property<DateTime?>("GradedDate")
                        .HasColumnType("date");

                    b.HasKey("GradedId");

                    b.HasIndex("FkCourseRegId");

                    b.HasIndex("FkCourseTeacherId");

                    b.HasIndex("FkGradeId");

                    b.ToTable("SeeGrades");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.GradeType", b =>
                {
                    b.Property<byte>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("GradeId"));

                    b.Property<string>("Grade")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("GradeId");

                    b.ToTable("GradeType", (string)null);
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.JobTitle", b =>
                {
                    b.Property<byte>("JobTitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("JobTitleId"));

                    b.Property<string>("JobTitle1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("JobTitle");

                    b.HasKey("JobTitleId");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.LatestMonthGradesView", b =>
                {
                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GradedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("LatestMonthGradesView", (string)null);
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.SeePersonnel", b =>
                {
                    b.Property<int>("PersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonnelId"));

                    b.Property<string>("Email")
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<byte?>("FkGenderId")
                        .HasColumnType("tinyint")
                        .HasColumnName("FK_GenderId");

                    b.Property<byte?>("FkJobTitleId")
                        .HasColumnType("tinyint")
                        .HasColumnName("FK_JobTitleId");

                    b.Property<string>("PhoneNr")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Ssn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("SSN");

                    b.Property<string>("Surname")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("PersonnelId");

                    b.HasIndex("FkGenderId");

                    b.HasIndex("FkJobTitleId");

                    b.HasIndex(new[] { "Ssn" }, "UQ_PersonnelSSN")
                        .IsUnique()
                        .HasFilter("[SSN] IS NOT NULL");

                    b.HasIndex(new[] { "Ssn" }, "UQ_Personnel_SSN")
                        .IsUnique()
                        .HasFilter("[SSN] IS NOT NULL");

                    b.ToTable("SeePersonnel");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int?>("FkClassId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ClassId");

                    b.Property<byte?>("FkGenderId")
                        .HasColumnType("tinyint")
                        .HasColumnName("FK_GenderId");

                    b.Property<string>("PhoneNr")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime?>("SchoolStart")
                        .HasColumnType("date");

                    b.Property<string>("Ssn")
                        .HasMaxLength(13)
                        .IsUnicode(false)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("SSN");

                    b.Property<string>("Surname")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("StudentId");

                    b.HasIndex("FkClassId");

                    b.HasIndex("FkGenderId");

                    b.HasIndex(new[] { "Ssn" }, "UQ_StudentSSN")
                        .IsUnique()
                        .HasFilter("[SSN] IS NOT NULL");

                    b.HasIndex(new[] { "Ssn" }, "UQ_Students_SSN")
                        .IsUnique()
                        .HasFilter("[SSN] IS NOT NULL");

                    b.ToTable("SeeStudents");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.ClassMentor", b =>
                {
                    b.HasOne("KrutangerHighSchoolDB.Models.ClassList", "FkClass")
                        .WithMany()
                        .HasForeignKey("FkClassId")
                        .HasConstraintName("FK_ClassMentor_ClassList");

                    b.HasOne("KrutangerHighSchoolDB.Models.SeePersonnel", "FkPersonnel")
                        .WithMany()
                        .HasForeignKey("FkPersonnelId")
                        .HasConstraintName("FK_ClassMentor_Personnel");

                    b.Navigation("FkClass");

                    b.Navigation("FkPersonnel");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.CourseRegistration", b =>
                {
                    b.HasOne("KrutangerHighSchoolDB.Models.Course", "FkCourse")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("FkCourseId")
                        .HasConstraintName("FK_CourseRegistration_Courses");

                    b.HasOne("KrutangerHighSchoolDB.Models.Student", "FkStudent")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("FkStudentId")
                        .HasConstraintName("FK_CourseRegistration_Students");

                    b.Navigation("FkCourse");

                    b.Navigation("FkStudent");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.CourseTeacher", b =>
                {
                    b.HasOne("KrutangerHighSchoolDB.Models.Course", "FkCourse")
                        .WithMany("CourseTeachers")
                        .HasForeignKey("FkCourseId")
                        .HasConstraintName("FK_CourseTeacher_Courses");

                    b.HasOne("KrutangerHighSchoolDB.Models.SeePersonnel", "FkPersonnel")
                        .WithMany("CourseTeachers")
                        .HasForeignKey("FkPersonnelId")
                        .HasConstraintName("FK_CourseTeacher_Personnel");

                    b.Navigation("FkCourse");

                    b.Navigation("FkPersonnel");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Grade", b =>
                {
                    b.HasOne("KrutangerHighSchoolDB.Models.CourseRegistration", "FkCourseReg")
                        .WithMany("SeeGrades")
                        .HasForeignKey("FkCourseRegId")
                        .HasConstraintName("FK_Grades_CourseRegistration");

                    b.HasOne("KrutangerHighSchoolDB.Models.CourseTeacher", "FkCourseTeacher")
                        .WithMany("SeeGrades")
                        .HasForeignKey("FkCourseTeacherId")
                        .HasConstraintName("FK_Grades_CourseTeacher");

                    b.HasOne("KrutangerHighSchoolDB.Models.GradeType", "FkGrade")
                        .WithMany("SeeGrades")
                        .HasForeignKey("FkGradeId")
                        .HasConstraintName("FK_Grades_GradeType");

                    b.Navigation("FkCourseReg");

                    b.Navigation("FkCourseTeacher");

                    b.Navigation("FkGrade");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.SeePersonnel", b =>
                {
                    b.HasOne("KrutangerHighSchoolDB.Models.Gender", "FkGender")
                        .WithMany("SeePersonnel")
                        .HasForeignKey("FkGenderId")
                        .HasConstraintName("FK_Personnel_Genders");

                    b.HasOne("KrutangerHighSchoolDB.Models.JobTitle", "FkJobTitle")
                        .WithMany("SeePersonnel")
                        .HasForeignKey("FkJobTitleId")
                        .HasConstraintName("FK_Personnel_JobTitles");

                    b.Navigation("FkGender");

                    b.Navigation("FkJobTitle");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Student", b =>
                {
                    b.HasOne("KrutangerHighSchoolDB.Models.ClassList", "FkClass")
                        .WithMany("SeeStudents")
                        .HasForeignKey("FkClassId")
                        .HasConstraintName("FK_Students_ClassList");

                    b.HasOne("KrutangerHighSchoolDB.Models.Gender", "FkGender")
                        .WithMany("SeeStudents")
                        .HasForeignKey("FkGenderId")
                        .HasConstraintName("FK_Students_Genders");

                    b.Navigation("FkClass");

                    b.Navigation("FkGender");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.ClassList", b =>
                {
                    b.Navigation("SeeStudents");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Course", b =>
                {
                    b.Navigation("CourseRegistrations");

                    b.Navigation("CourseTeachers");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.CourseRegistration", b =>
                {
                    b.Navigation("SeeGrades");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.CourseTeacher", b =>
                {
                    b.Navigation("SeeGrades");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Gender", b =>
                {
                    b.Navigation("SeePersonnel");

                    b.Navigation("SeeStudents");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.GradeType", b =>
                {
                    b.Navigation("SeeGrades");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.JobTitle", b =>
                {
                    b.Navigation("SeePersonnel");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.SeePersonnel", b =>
                {
                    b.Navigation("CourseTeachers");
                });

            modelBuilder.Entity("KrutangerHighSchoolDB.Models.Student", b =>
                {
                    b.Navigation("CourseRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
